// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwK0OWgbOkWL8F2jcRQ-pKzxooHRNhTyA',
    appId: '1:69815876642:web:a8d773c7053828b60c5e7b',
    messagingSenderId: '69815876642',
    projectId: 'online-learning-app-aea3e',
    authDomain: 'online-learning-app-aea3e.firebaseapp.com',
    storageBucket: 'online-learning-app-aea3e.appspot.com',
    measurementId: 'G-NQ6YKMFL6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wNBnh293QebUXpfBe9rLVo85dxQQm7U',
    appId: '1:69815876642:android:a167b871c243c8e80c5e7b',
    messagingSenderId: '69815876642',
    projectId: 'online-learning-app-aea3e',
    storageBucket: 'online-learning-app-aea3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDucLN89zZ0SDrxUlHaZrnINlEkMjQ6WV0',
    appId: '1:69815876642:ios:20dd3d57dee8d74a0c5e7b',
    messagingSenderId: '69815876642',
    projectId: 'online-learning-app-aea3e',
    storageBucket: 'online-learning-app-aea3e.appspot.com',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDucLN89zZ0SDrxUlHaZrnINlEkMjQ6WV0',
    appId: '1:69815876642:ios:20dd3d57dee8d74a0c5e7b',
    messagingSenderId: '69815876642',
    projectId: 'online-learning-app-aea3e',
    storageBucket: 'online-learning-app-aea3e.appspot.com',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwK0OWgbOkWL8F2jcRQ-pKzxooHRNhTyA',
    appId: '1:69815876642:web:d9267af4e3dfa62d0c5e7b',
    messagingSenderId: '69815876642',
    projectId: 'online-learning-app-aea3e',
    authDomain: 'online-learning-app-aea3e.firebaseapp.com',
    storageBucket: 'online-learning-app-aea3e.appspot.com',
    measurementId: 'G-J722G5V693',
  );
}
